Feature/update data owner
tokend/xdr pull request #118
Opened 2022-08-17 11:50 UTC by ivanlele

2022-08-18 19:10 UTC, 1henny requested changes

2022-08-18 19:10 UTC, 1henny commented on operation-update-data-owner.x
> +    //: Reserved for future extension
here we should provide new owner's ID

2022-08-18 19:10 UTC, 1henny commented on operation-update-data-owner.x
> +    AccountID owner;
let's name it `destination` or `new_owner` as it is more descriptive

2022-08-18 19:10 UTC, 1henny commented on operation-update-data-owner.x
> +    AccountID owner;
also update docs for the `owner` field of `DataEntry`

2022-08-18 19:10 UTC, 1henny commented on docs/paths/update_data_owner_op.yaml
> +                    | source  | `DATA`        | `UPDATE_OWNER_FOR_OTHER`    | source `accountID` is **not** equal to data owner | Resource contains data type |
- rule action should be named `TRANSFER_OWNERSHIP`
- we should not have `*_FOR_OTHER` action for this operation as it opens the probable attack vector
- add `TRANSFER_OWNERSHIP` to resource-account-rule.x and resource-signer-rule.x

2022-08-18 19:10 UTC, 1henny commented on operation-update-data-owner.x
> +struct UpdateDataOwnerOp
we also need a reviewable request for this operation

2022-08-18 19:10 UTC, 1henny commented on operation-update-data-owner.x
> +    INVALID_DATA = -1,
`AccountID` type restricts the range of values that may be used in this field so this error code is not needed

2022-08-19 11:24 UTC, 1henny requested changes

2022-08-19 11:24 UTC, 1henny commented on ledger-entries-reviewable-request.x
> +		case DATA_OWNER_UPDATE:
fix indentation

2022-08-19 11:24 UTC, 1henny commented on operation-create-data-owner-update-request.x
> +    UPDATE_DATA_TASKS_NOT_FOUND = -2,
update_data_tasks are related to update_data operation and not to update_data_owner. I think it should not be here

2022-08-19 11:28 UTC, artemskriabin requested changes

2022-08-19 11:28 UTC, artemskriabin commented on resource-account-rule.x
> +        uint64 type;
it could rule for the reviewable request

2022-08-19 11:28 UTC, artemskriabin commented on operation-update-data-owner.x
> +    AccountID new_owner;
new owner is specified in the request

2022-08-19 11:28 UTC, artemskriabin commented on reviewable-request-update-data-owner.x
> +    AccountID new_owner;
snake case

2022-08-20 17:07 UTC, 1henny requested changes

2022-08-20 17:07 UTC, 1henny commented on ledger-entries-reviewable-request.x
> +    CLOSE_DEFERRED_PAYMENT = 26,
fix indentation

2022-08-20 17:07 UTC, 1henny commented on reviewable-request-update-data-owner.x
> +    uint64 id;
we can use operation field here as in reviewable-request-payment.x

2022-08-22 12:10 UTC, 1henny requested changes

2022-08-22 12:10 UTC, 1henny commented on reviewable-request-update-data-owner.x
> +    AccountID newOwner;
it is already inside `updateDataOwnerOp`

2022-08-31 13:36 UTC, 1henny approved these changes

2022-08-31 14:39 UTC, artemskriabin approved these changes

2022-08-31 16:59 UTC, merged