Added update poll end time & cancel poll operations
tokend/xdr pull request #57
Opened 2019-04-23 14:21 UTC by khramoff

2019-04-24 13:36 UTC, artemskriabin commented on Stellar-operation-manage-poll.x
> +    //:Only poll owner and admin can cancel poll
As I know space after `//:` reuired

2019-04-24 13:36 UTC, artemskriabin commented on Stellar-operation-manage-poll.x
> +    //:Only poll owner can update end time
or admin

2019-04-24 13:40 UTC, artemskriabin commented on Stellar-operation-manage-poll.x
> +    //:Only poll owner can update end time
use one error code for both cases (not auth for cancel and update) - just `NOT_AUTHORIZED`
client knows which action he tries to apply

2019-04-24 14:36 UTC, artemskriabin submitted a review, later dismissed

2019-04-29 17:43 UTC, dhaidashenko requested changes

2019-04-29 17:43 UTC, dhaidashenko commented on docs/paths/update_poll_end_time.yaml
> +                  Allows update poll end time. Only admin or poll owner can cancel poll.
Cancel?

2019-05-02 10:31 UTC, dhaidashenko submitted a review, later dismissed

2019-05-02 10:36 UTC, dhaidashenko approved these changes

2019-05-02 10:36 UTC, merged